### PR TITLE
fix: appmap.Recording is available even when APPMAP=false

### LINKED ISSUE #326: `appmap.Recording` is available even when `APPMAP=false`
Code that imports `appmap.Recording` should run correctly even when `not Env.current.enabled`.

It may be possible to implement this by simply moving the import from `_appmap` outside the current `if..then` that's keeping it from being imported.

### PR DESCRIPTION
**Pull request by zermelo-wisen**
Fixes #326.

- Adds `NoopRecording` class with the same interface as `Recording`.
- Exports `NoopRecording` as `Recording` when `APPMAP` is not set to `true` to prevent "ImportError: cannot import name 'Recording' from 'appmap' ..." in client code.
- Extends [`smoketest.sh`](https://github.com/getappmap/appmap-python/blob/325a58b7981f7e994626b29193ba89e4814bc8d4/ci/smoketest.sh#L31-L48) to ensure that client code using `appmap.Recording` does not fail when `APPMAP=false`.

### CODE REVIEW

File: ci/smoketest.sh [hunk 1]
```diff
@@ -27,3 +27,22 @@ else
   find $PWD
   exit 1
 fi
+
+# Ensure that client code using appmap.Recording does not fail when APPMAP=false
```
Comment (apotterri) [inline ci/smoketest.sh:31]: This can get moved up before https://github.com/getappmap/appmap-python/pull/327/files#diff-ba2ff002750238ee03b3467fd4400804141c8aa2606bdd4263f0a3636bb120c1R12 to avoid flipping `APPMAP` on and off.

This file is starting to get kind of complicated. Please move this test into a separate function. Thanks!

**Review by apotterri — CHANGES_REQUESTED** [review]
Thanks for this, looks good. One minor change and it'll be ready to go.

**Review by apotterri — APPROVED** [review]
Thanks, good to go.
